version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mysecretpassword  # Change this as needed
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Neo4j Bolt
    environment:
      - NEO4J_AUTH=neo4j/mysecretpassword  # Set your password here
