version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ARANGODB_URL=http://arangodb:8529  # URL for ArangoDB
      - ARANGODB_DB=yourDatabaseName  # Change this to your desired database name
      - ARANGODB_USER=root  # Default username for ArangoDB
      - ARANGODB_PASSWORD=admin  # Set your application password to 'admin'
    depends_on:
      - arangodb

  arangodb:
    image: arangodb:latest
    ports:
      - "8529:8529"  # ArangoDB HTTP API
    environment:
      - ARANGO_ROOT_PASSWORD=admin  # Set the root password to 'admin'
      - ARANGO_DATABASE=yourDatabaseName  # Optionally, create a database at startup
    volumes:
      - arangodb_data:/var/lib/arangodb3  # Persist data

volumes:
  arangodb_data:
